// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingEngine.Infrastructure.Persistence;

#nullable disable

namespace TradingEngine.Infrastructure.Persistence.Migrations;
[DbContext(typeof(TradingEngineDbContext))]
[Migration("20260918172032_InitialCurrentConfiguration")]
partial class InitialCurrentConfiguration
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.ChartAnalysisDefinitionRow", b =>
            {
                b.Property<Guid>("WatchedInstrumentId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("DefinitionXml")
                    .IsRequired()
                    .HasColumnType("xml");

                b.HasKey("WatchedInstrumentId");

                b.ToTable("ChartAnalysisDefinitions", (string)null);
            });

        modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.WatchedInstrumentRow", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2(7)");

                b.Property<string>("Exchange")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<DateTime>("LastChangedAt")
                    .HasColumnType("datetime2(7)");

                b.Property<string>("MonitoringState")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("nvarchar(16)");

                b.Property<string>("QuoteCurrency")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.Property<int>("SamplingIntervalSeconds")
                    .HasColumnType("int");

                b.Property<string>("Symbol")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)");

                b.HasKey("Id");

                b.HasIndex("Exchange", "Symbol", "QuoteCurrency")
                    .IsUnique()
                    .HasDatabaseName("UX_WatchedInstruments_Exchange_Symbol_QuoteCurrency");

                b.ToTable("WatchedInstruments", null, t =>
                    {
                        t.HasCheckConstraint("CK_WatchedInstruments_ChangeTimestamps", "[LastChangedAt] >= [CreatedAt]");

                        t.HasCheckConstraint("CK_WatchedInstruments_MonitoringState", "[MonitoringState] IN ('Configured', 'Monitored')");

                        t.HasCheckConstraint("CK_WatchedInstruments_SamplingIntervalSeconds", "[SamplingIntervalSeconds] >= 1 AND [SamplingIntervalSeconds] <= 3600");
                    });
            });

        modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.ChartAnalysisDefinitionRow", b =>
            {
                b.HasOne("TradingEngine.Infrastructure.Persistence.WatchedInstrumentRow", "Instrument")
                    .WithOne("ChartAnalysisDefinition")
                    .HasForeignKey("TradingEngine.Infrastructure.Persistence.ChartAnalysisDefinitionRow", "WatchedInstrumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Instrument");
            });

        modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.WatchedInstrumentRow", b =>
            {
                b.Navigation("ChartAnalysisDefinition");
            });
#pragma warning restore 612, 618
    }
}
