// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingEngine.Infrastructure.Persistence;

#nullable disable

namespace TradingEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingEngineDbContext))]
    [Migration("20261003150626_MonitoringRuleRevisionHistory")]
    partial class MonitoringRuleRevisionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.ChartAnalysisDefinitionRow", b =>
                {
                    b.Property<Guid>("WatchedInstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefinitionXml")
                        .IsRequired()
                        .HasColumnType("xml");

                    b.HasKey("WatchedInstrumentId");

                    b.ToTable("ChartAnalysisDefinitions", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.MonitoringRuleRevisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DefinitionXml")
                        .IsRequired()
                        .HasColumnType("xml");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("MonitoringRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ProposedFrom")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("ProposedTo")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("RevisionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonitoringRuleId", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_MonitoringRuleRevisions_EffectiveFrom")
                        .HasFilter("[EffectiveFrom] IS NOT NULL");

                    b.HasIndex("MonitoringRuleId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_MonitoringRuleRevisions_RevisionNumber")
                        .HasFilter("[RevisionNumber] IS NOT NULL");

                    b.ToTable("MonitoringRuleRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_MonitoringRuleRevisions_Numbering", "([EffectiveFrom] IS NULL AND [RevisionNumber] IS NULL) OR ([EffectiveFrom] IS NOT NULL AND [RevisionNumber] IS NOT NULL AND [RevisionNumber] > 0)");

                            t.HasCheckConstraint("CK_MonitoringRuleRevisions_Period", "([EffectiveFrom] IS NULL AND [EffectiveTo] IS NULL) OR ([EffectiveFrom] IS NOT NULL AND ([EffectiveTo] IS NULL OR [EffectiveTo] > [EffectiveFrom]))");
                        });
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.MonitoringRuleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WatchedInstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WatchedInstrumentId")
                        .IsUnique()
                        .HasDatabaseName("UX_MonitoringRules_WatchedInstrumentId");

                    b.ToTable("MonitoringRules", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.WatchedInstrumentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LastChangedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("MonitoringState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SamplingIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Exchange", "Symbol", "QuoteCurrency")
                        .IsUnique()
                        .HasDatabaseName("UX_WatchedInstruments_Exchange_Symbol_QuoteCurrency");

                    b.ToTable("WatchedInstruments", null, t =>
                        {
                            t.HasCheckConstraint("CK_WatchedInstruments_ChangeTimestamps", "[LastChangedAt] >= [CreatedAt]");

                            t.HasCheckConstraint("CK_WatchedInstruments_MonitoringState", "[MonitoringState] IN ('Configured', 'Monitored')");

                            t.HasCheckConstraint("CK_WatchedInstruments_SamplingIntervalSeconds", "[SamplingIntervalSeconds] >= 1 AND [SamplingIntervalSeconds] <= 3600");
                        });
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.ChartAnalysisDefinitionRow", b =>
                {
                    b.HasOne("TradingEngine.Infrastructure.Persistence.WatchedInstrumentRow", "Instrument")
                        .WithOne("ChartAnalysisDefinition")
                        .HasForeignKey("TradingEngine.Infrastructure.Persistence.ChartAnalysisDefinitionRow", "WatchedInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.MonitoringRuleRevisionRow", b =>
                {
                    b.HasOne("TradingEngine.Infrastructure.Persistence.MonitoringRuleRow", "Rule")
                        .WithMany("Revisions")
                        .HasForeignKey("MonitoringRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.MonitoringRuleRow", b =>
                {
                    b.HasOne("TradingEngine.Infrastructure.Persistence.WatchedInstrumentRow", "Instrument")
                        .WithOne()
                        .HasForeignKey("TradingEngine.Infrastructure.Persistence.MonitoringRuleRow", "WatchedInstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.MonitoringRuleRow", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.WatchedInstrumentRow", b =>
                {
                    b.Navigation("ChartAnalysisDefinition");
                });
#pragma warning restore 612, 618
        }
    }
}
